// <auto-generated />
using System;
using GestionSalle.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionSalle.Migrations
{
    [DbContext(typeof(SalleDbContext))]
    partial class SalleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionSalle.Models.Entraineur", b =>
                {
                    b.Property<int>("IdEntraineur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEntraineur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntraineur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nomComplet");

                    b.Property<string>("Specialite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("specialite");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Actif")
                        .HasColumnName("statut");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdEntraineur")
                        .HasName("PK__Entraine__72EED92B4C108FDE");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex(new[] { "Email" }, "UQ__Entraine__AB6E61647760B8E4")
                        .IsUnique();

                    b.ToTable("Entraineur", (string)null);
                });

            modelBuilder.Entity("GestionSalle.Models.Membre", b =>
                {
                    b.Property<int>("IdMembre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMembre");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembre"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateInscription")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("IdEntraineur")
                        .HasColumnType("int")
                        .HasColumnName("idEntraineur");

                    b.Property<int?>("IdPlan")
                        .HasColumnType("int")
                        .HasColumnName("idPlan");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nomComplet");

                    b.Property<string>("Sexe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sexe");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Actif")
                        .HasColumnName("statut");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdMembre")
                        .HasName("PK__Membre__7399C5D7C144F10B");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex(new[] { "Email" }, "IX_Membre_Email");

                    b.HasIndex(new[] { "IdEntraineur" }, "IX_Membre_IdEntraineur");

                    b.HasIndex(new[] { "Statut" }, "IX_Membre_Statut");

                    b.HasIndex(new[] { "Email" }, "UQ__Membre__AB6E616470938203")
                        .IsUnique();

                    b.ToTable("Membre", (string)null);
                });

            modelBuilder.Entity("GestionSalle.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPaiement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("datePaiement")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("idMembre");

                    b.Property<string>("Methode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("methode");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("montant");

                    b.HasKey("IdPaiement")
                        .HasName("PK__Paiement__D44CB63D57A3FA4F");

                    b.HasIndex(new[] { "DatePaiement" }, "IX_Paiement_Date");

                    b.HasIndex(new[] { "IdMembre" }, "IX_Paiement_IdMembre");

                    b.ToTable("Paiement", (string)null);
                });

            modelBuilder.Entity("GestionSalle.Models.PlanAbonnement", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPlan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlan"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("DureeEnMois")
                        .HasColumnType("int")
                        .HasColumnName("dureeEnMois");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prix");

                    b.HasKey("IdPlan")
                        .HasName("PK__PlanAbon__BECFB99658F303DF");

                    b.ToTable("PlanAbonnement", (string)null);
                });

            modelBuilder.Entity("GestionSalle.Models.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSeance");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeance"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("IdEntraineur")
                        .HasColumnType("int")
                        .HasColumnName("idEntraineur");

                    b.Property<int?>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("idMembre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.HasKey("IdSeance")
                        .HasName("PK__Seance__7CD10F7DD39F6B82");

                    b.HasIndex("IdEntraineur");

                    b.HasIndex("IdMembre");

                    b.HasIndex(new[] { "Date" }, "IX_Seance_Date");

                    b.ToTable("Seance", (string)null);
                });

            modelBuilder.Entity("GestionSalle.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreation")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("motDePasse");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nomUtilisateur");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Utilisat__5366DB1936444C3D");

                    b.HasIndex(new[] { "Role" }, "IX_Utilisateur_Role");

                    b.HasIndex(new[] { "NomUtilisateur" }, "UQ__Utilisat__BD52466D01D110EF")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("GestionSalle.Models.Entraineur", b =>
                {
                    b.HasOne("GestionSalle.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany("Entraineurs")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Entraineu__idUti__76969D2E");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("GestionSalle.Models.Membre", b =>
                {
                    b.HasOne("GestionSalle.Models.Entraineur", "IdEntraineurNavigation")
                        .WithMany("Membres")
                        .HasForeignKey("IdEntraineur")
                        .HasConstraintName("FK__Membre__idEntrai__7F2BE32F");

                    b.HasOne("GestionSalle.Models.PlanAbonnement", "IdPlanNavigation")
                        .WithMany("Membres")
                        .HasForeignKey("IdPlan")
                        .HasConstraintName("FK__Membre__idPlan__7E37BEF6");

                    b.HasOne("GestionSalle.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany("Membres")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Membre__idUtilis__00200768");

                    b.Navigation("IdEntraineurNavigation");

                    b.Navigation("IdPlanNavigation");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("GestionSalle.Models.Paiement", b =>
                {
                    b.HasOne("GestionSalle.Models.Membre", "IdMembreNavigation")
                        .WithMany("Paiements")
                        .HasForeignKey("IdMembre")
                        .IsRequired()
                        .HasConstraintName("FK__Paiement__idMemb__0E6E26BF");

                    b.Navigation("IdMembreNavigation");
                });

            modelBuilder.Entity("GestionSalle.Models.Seance", b =>
                {
                    b.HasOne("GestionSalle.Models.Entraineur", "IdEntraineurNavigation")
                        .WithMany("Seances")
                        .HasForeignKey("IdEntraineur")
                        .HasConstraintName("FK__Seance__idEntrai__03F0984C");

                    b.HasOne("GestionSalle.Models.Membre", "IdMembreNavigation")
                        .WithMany("Seances")
                        .HasForeignKey("IdMembre")
                        .HasConstraintName("FK__Seance__idMembre__02FC7413");

                    b.Navigation("IdEntraineurNavigation");

                    b.Navigation("IdMembreNavigation");
                });

            modelBuilder.Entity("GestionSalle.Models.Entraineur", b =>
                {
                    b.Navigation("Membres");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionSalle.Models.Membre", b =>
                {
                    b.Navigation("Paiements");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionSalle.Models.PlanAbonnement", b =>
                {
                    b.Navigation("Membres");
                });

            modelBuilder.Entity("GestionSalle.Models.Utilisateur", b =>
                {
                    b.Navigation("Entraineurs");

                    b.Navigation("Membres");
                });
#pragma warning restore 612, 618
        }
    }
}
